config/routes.rb
Rails.application.routes.draw do

  get "pages/index"
  get "pages/about"
  get "pages/features"
  get "pages/contact"
  get "pages/login"
  get "pages/pricing"
  get "pages/register"

  root 'pages#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Mini Ruby</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <%= stylesheet_link_tag  "application", "bootstrap", "bootstrap-responsive", "font", "font-awesome", "base.css", "blue.css"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="img/favicon.ico">
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<%= asset_path('img/favicon.ico')%>">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<%= asset_path('img/favicon.ico')%>">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<%= asset_path('img/favicon.ico')%>">
  <link rel="apple-touch-icon-precomposed" href="<%= asset_path('img/favicon.ico')%>">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container"> <a class="btn btn-primary btn-dropnav" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a> <a class="brand" href="index.html"><img src="<%= asset_path('img/logo.gif')%>" alt="" border="0"></a>
      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
          <li class="active"><a href="index.html">Home</a></li>
          <li><a href="<%= pages_about_path %>">About</a></li>
          <li><a href="<%= pages_features_path %>">Features</a></li>
          <li><a href="<%= pages_pricing_path %>">Pricing</a></li>
          <li><a href="<%= pages_login_path %>">Login</a></li>
          <li><a href="<%= pages_register_path %>">Register</a></li>
          <li><a href="<%= pages_contact_path %>">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<%= yield %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script>
  $(document).ready(function(){
    $(".js-video").fitVids();
      $("#totop").click(function () {
    $("body, html").animate({
      scrollTop: 0
      }, 300);
    return false;
    }); 
  });
  </script>
</body>
</html>

app/views/pages/about.html.erb
<div id="header">
  <div class="container">
    <div class="row">
      <div class="span12">
        <h1>About Bounce</h1>
      </div>
    </div>
  </div>
</div>
<div id="content">
  <div class="container">
    <div class="row">
      <div class="span6">
        <h2>Our Mission</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent arcu massa, consequat nec venenatis vel, vehicula in felis. Donec dapibus tortor consequat turpis fringilla rutrum. Nulla porta turpis massa. Vivamus facilisis pretium mauris, ac varius augue posuere eget. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
      </div>
      <div class="span6">
        <h2>Header</h2>
        <p>Cras vehicula orci mauris, sed porta tellus. Phasellus id odio eget elit convallis placerat sit amet sodales quam. Mauris sit amet diam vel ligula bibendum porta eu a magna. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
      </div>
    </div>
    <div class="row">
      <div class="span12">
        <h2 class="txt-middle">Our Team</h2>
        <hr class="dashed">
      </div>
    </div>
    <div class="row">
      <div class="span12">
        <ul class="thumbnails">
          <li class="span3">
            <div id="team" class="thumbnail"> <img alt="" src="http://quickimage.it/300x180">
              <div class="caption">
                <h4>John Smith</h4>
                <p><em>Founder</em></p>
                <div class="social">
                  <ul class="unstyled">
                    <li><a class="facebook" href=""><i class="icon-facebook-sign"></i></a></li>
                    <li><a class="twitter" href=""><i class="icon-twitter-sign"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </li>
          <li class="span3">
            <div id="team" class="thumbnail"> <img alt="" src="http://quickimage.it/300x180">
              <div class="caption">
                <h4>John Smith</h4>
                <p><em>Founder</em></p>
                <div class="social">
                  <ul class="unstyled">
                    <li><a class="facebook" href=""><i class="icon-facebook-sign"></i></a></li>
                    <li><a class="twitter" href=""><i class="icon-twitter-sign"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </li>
          <li class="span3">
            <div id="team" class="thumbnail"> <img alt="" src="http://quickimage.it/300x180">
              <div class="caption">
                <h4>John Smith</h4>
                <p><em>Founder</em></p>
                <div class="social">
                  <ul class="unstyled">
                    <li><a class="facebook" href=""><i class="icon-facebook-sign"></i></a></li>
                    <li><a class="twitter" href=""><i class="icon-twitter-sign"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </li>
          <li class="span3">
            <div id="team" class="thumbnail"> <img alt="" src="http://quickimage.it/300x180">
              <div class="caption">
                <h4>John Smith</h4>
                <p><em>Founder</em></p>
                <div class="social">
                  <ul class="unstyled">
                    <li><a class="facebook" href=""><i class="icon-facebook-sign"></i></a></li>
                    <li><a class="twitter" href=""><i class="icon-twitter-sign"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </li>
          <li class="span3">
            <div id="team" class="thumbnail"> <img alt="" src="http://quickimage.it/300x180">
              <div class="caption">
                <h4>John Smith</h4>
                <p><em>Founder</em></p>
                <div class="social">
                  <ul class="unstyled">
                    <li><a class="facebook" href=""><i class="icon-facebook-sign"></i></a></li>
                    <li><a class="twitter" href=""><i class="icon-twitter-sign"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </li>
          <li class="span3">
            <div id="team" class="thumbnail"> <img alt="" src="http://quickimage.it/300x180">
              <div class="caption">
                <h4>John Smith</h4>
                <p><em>Founder</em></p>
                <div class="social">
                  <ul class="unstyled">
                    <li><a class="facebook" href=""><i class="icon-facebook-sign"></i></a></li>
                    <li><a class="twitter" href=""><i class="icon-twitter-sign"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </li>
          <li class="span3">
            <div id="team" class="thumbnail"> <img alt="" src="http://quickimage.it/300x180">
              <div class="caption">
                <h4>John Smith</h4>
                <p><em>Founder</em></p>
                <div class="social">
                  <ul class="unstyled">
                    <li><a class="facebook" href=""><i class="icon-facebook-sign"></i></a></li>
                    <li><a class="twitter" href=""><i class="icon-twitter-sign"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </li>
          <li class="span3">
            <div id="team" class="thumbnail"> <img alt="" src="http://quickimage.it/300x180">
              <div class="caption">
                <h4>John Smith</h4>
                <p><em>Founder</em></p>
                <div class="social">
                  <ul class="unstyled">
                    <li><a class="facebook" href=""><i class="icon-facebook-sign"></i></a></li>
                    <li><a class="twitter" href=""><i class="icon-twitter-sign"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div id="footer">
  <div class="container">
    <div class="row">
      <div class="span3">
        <h3>Quick Links</h3>
        <ul>
          <li><a href="<%= root_path %>">Home</a></li>
          <li><a href="<%= pages_about_path %>">About Us</a></li>
          <li><a href="<%= pages_features_path %>">Features</a></li>
          <li><a href="<%= pages_pricing_path %>">Pricing</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Company</h3>
        <ul>
          <li><a href="#">Privacy Policy</a></li>
          <li><a href="#">Terms of Use</a></li>
          <li><a href="#">Faq</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Social Media</h3>
        <ul>
          <li><a href="#">Facebook</a></li>
          <li><a href="http://www.twitter.com/railsview">Twitter</a></li>
          <li><a href="#">Dribbble</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div id="copywrite">
  <div class="container">
    <div class="row">
      <div class="span12">
        <p>&copy; Mini Ruby <span id="totop" class="pull-right">Back to Top</span></p>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div id="header">
  <div class="container">
    <div class="row">
      <div class="span12">
        <h1>Contact Us</h1>
      </div>
    </div>
  </div>
</div>
<div id="content">
  <div class="container">
    <div class="row">
      <div class="span5">
        <h2><i class="icon-envelope"></i> Email Us</h2>
        <fieldset>
        <div class="control-group">
          <div class="controls">
            <input class="span5" type="text" placeholder="Your Full Name">
          </div>
          <div class="controls">
            <input class="span5" type="text" placeholder="Your Email">
          </div>
          <div class="controls">
            <input class="span5" type="text" placeholder="Message Subject">
          </div>
          <div class="controls">
            <textarea class="span5" id="textarea" rows="6" placeholder="Your Message"></textarea>
          </div>
          <button class="btn btn-primary">Send Message</button>
        </div>
        </fieldset>
      </div>
      <div class="span7">
        <div class="row">
          <div class="span3">
            <h2><i class="icon-map-marker"></i> Address</h2>
            <address>
            111 Some Street, Suite 100 <br>
            San Francisco, CA 94107
            </address>
          </div>
          <div class="span4">
            <h2><i class="icon-phone"></i> Phone</h2>
            <address>
            Phone: (123) 456-7890 <br>
            Fax: (123) 456-7890
            </address>
          </div>
        </div>
        <div> <img border="0" alt="" src="http://maps.googleapis.com/maps/api/staticmap?center=Brooklyn+Bridge,New+York,NY&zoom=14&size=840x230&maptype=roadmap&sensor=false"> </div>
      </div>
    </div>
    <hr class="space">
  </div>
</div>

<div id="footer">
  <div class="container">
    <div class="row">
      <div class="span3">
        <h3>Quick Links</h3>
        <ul>
          <li><a href="<%= root_path %>">Home</a></li>
          <li><a href="<%= pages_about_path %>">About Us</a></li>
          <li><a href="<%= pages_features_path %>">Features</a></li>
          <li><a href="<%= pages_pricing_path %>">Pricing</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Company</h3>
        <ul>
          <li><a href="#">Privacy Policy</a></li>
          <li><a href="#">Terms of Use</a></li>
          <li><a href="#">Faq</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Social Media</h3>
        <ul>
          <li><a href="#">Facebook</a></li>
          <li><a href="http://www.twitter.com/railsview">Twitter</a></li>
          <li><a href="#">Dribbble</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div id="copywrite">
  <div class="container">
    <div class="row">
      <div class="span12">
        <p>&copy; Mini Ruby <span id="totop" class="pull-right">Back to Top</span></p>
      </div>
    </div>
  </div>
</div>

app/views/pages/features.html.erb
<div id="header">
  <div class="container">
    <div class="row">
      <div class="span12">
        <h1>Our Awesome Features</h1>
      </div>
    </div>
  </div>
</div>
<div id="content">
  <div class="container">
    <div class="row">
      <div class="span4"> <a class="thumbnail" href=""> <img alt="image" src="http://placehold.it/300x150"> </a>
        <h2 class="sub">One Great Feature</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent arcu massa, consequat nec venenatis vel, vehicula in felis. Donec dapibus tortor consequat turpis fringilla rutrum.</p>
      </div>
      <div class="span4"> <a class="thumbnail" href=""> <img alt="image" src="http://placehold.it/300x150"> </a>
        <h2 class="sub">One Great Feature</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent arcu massa, consequat nec venenatis vel, vehicula in felis. Donec dapibus tortor consequat turpis fringilla rutrum.</p>
      </div>
      <div class="span4"> <a class="thumbnail" href=""> <img alt="image" src="http://placehold.it/300x150"> </a>
        <h2 class="sub">One Great Feature</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent arcu massa, consequat nec venenatis vel, vehicula in felis. Donec dapibus tortor consequat turpis fringilla rutrum.</p>
      </div>
    </div>
    <hr class="dashed">
    <div class="row">
      <div class="span4"> <a class="thumbnail" href=""> <img alt="image" src="http://placehold.it/300x150"> </a>
        <h2 class="sub">One Great Feature</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent arcu massa, consequat nec venenatis vel, vehicula in felis. Donec dapibus tortor consequat turpis fringilla rutrum.</p>
      </div>
      <div class="span4"> <a class="thumbnail" href=""> <img alt="image" src="http://placehold.it/300x150"> </a>
        <h2 class="sub">One Great Feature</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent arcu massa, consequat nec venenatis vel, vehicula in felis. Donec dapibus tortor consequat turpis fringilla rutrum.</p>
      </div>
      <div class="span4"> <a class="thumbnail" href=""> <img alt="image" src="http://placehold.it/300x150"> </a>
        <h2 class="sub">One Great Feature</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent arcu massa, consequat nec venenatis vel, vehicula in felis. Donec dapibus tortor consequat turpis fringilla rutrum.</p>
      </div>
    </div>
    <div class="row">
      <div class="span12">
        <div class="callout well">
          <h2>Try our service free for 30 days</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipiscing elit arcu massa, vehicula in felis.</p>
          <a href="#" class="btn btn-primary btn-action">Get Started Now <i class="icon-arrow-right"></i></a> </div>
      </div>
    </div>
    <hr class="space">
  </div>
</div>

<div id="footer">
  <div class="container">
    <div class="row">
      <div class="span3">
        <h3>Quick Links</h3>
        <ul>
          <li><a href="<%= root_path %>">Home</a></li>
          <li><a href="<%= pages_about_path %>">About Us</a></li>
          <li><a href="<%= pages_features_path %>">Features</a></li>
          <li><a href="<%= pages_pricing_path %>">Pricing</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Company</h3>
        <ul>
          <li><a href="#">Privacy Policy</a></li>
          <li><a href="#">Terms of Use</a></li>
          <li><a href="#">Faq</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Social Media</h3>
        <ul>
          <li><a href="#">Facebook</a></li>
          <li><a href="http://www.twitter.com/railsview">Twitter</a></li>
          <li><a href="#">Dribbble</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div id="copywrite">
  <div class="container">
    <div class="row">
      <div class="span12">
        <p>&copy; Mini Ruby <span id="totop" class="pull-right">Back to Top</span></p>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div id="landing">
  <div class="container">
    <div class="row">
      <div class="span5">
        <h1>Groundbreaking<br>
          new video</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin venenatis dolor vel quam condimentum congue tempor nisl adipiscing. Fusce vehicula facilisis tortor, non eleifend orci vestibulum sed. In vestibulum, orci varius sagittis ultrices, augue </p>
        <p><a href="#" class="btn btn-primary btn-action">View Project</a></p>
      </div>
      <div class="span7">
        <div class="js-video">
          <iframe src="http://player.vimeo.com/video/44771465?title=0&amp;byline=0&amp;portrait=0&amp;badge=0" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="content" class="txt-middle">
  <div class="container">
    <div class="row main-tab">
      <div class="span4 bouncy">
      <div class="divider">
        <div class="icon_wrapper"> <i class="icon-comments"></i> </div>
        <h2>Testimonials</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin venenatis dolor Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin venenatis dolor v</p>
        </div>
      </div>
      <div class="span4 bouncy">
      <div class="divider">
        <div class="icon_wrapper"> <i class="icon-delicious-sign"></i> </div>
        <h2>Testimonials</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin venenatis dolor Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin venenatis dolor v</p>
        </div>
      </div>
      <div class="span4 bouncy">
      <div class="divider last">
        <div class="icon_wrapper"> <i class="icon-paste"></i> </div>
        <h2>Testimonials</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin venenatis dolor Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin venenatis dolor v</p>
        </div>
      </div>
    </div>
  </div>
  <div class="featured-container">
    <div class="container">
      <div class="row">
        <h2>Featured Projects</h2>
        <div class="span4"> <a href="" class="thumbnail"> <img alt="image" src="http://quickimage.it/400x200"></a></div>
        <div class="span4"> <a href="" class="thumbnail"> <img alt="image" src="http://quickimage.it/400x200"> </a></div>
        <div class="span4"> <a href="" class="thumbnail"> <img alt="image" src="http://quickimage.it/400x200"> </a></div>
      </div>
    </div>
  </div>
</div>

<div id="footer">
  <div class="container">
    <div class="row">
      <div class="span3">
        <h3>Quick Links</h3>
        <ul>
          <li><a href="<%= root_path %>">Home</a></li>
          <li><a href="<%= pages_about_path %>">About Us</a></li>
          <li><a href="<%= pages_features_path %>">Features</a></li>
          <li><a href="<%= pages_pricing_path %>">Pricing</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Company</h3>
        <ul>
          <li><a href="#">Privacy Policy</a></li>
          <li><a href="#">Terms of Use</a></li>
          <li><a href="#">Faq</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Social Media</h3>
        <ul>
          <li><a href="#">Facebook</a></li>
          <li><a href="http://www.twitter.com/railsview">Twitter</a></li>
          <li><a href="#">Dribbble</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div id="copywrite">
  <div class="container">
    <div class="row">
      <div class="span12">
        <p>&copy; Mini Ruby <span id="totop" class="pull-right">Back to Top</span></p>
      </div>
    </div>
  </div>
</div>

app/views/pages/login.html.erb
<div id="content" class="txt-middle">
  <div class="container">
    <div class="row">
      <div class="span12">
        <div class="modal modal-flat">
          <div class="modal-header">
            <h3>Login to Bounce</h3>
          </div>
          <div class="modal-body">
            <fieldset>
            <div class="control-group">
              <div class="controls">
                <div class="input-prepend"> <span class="add-on"><i class="icon-user"></i></span>
                  <input type="text" placeholder="Username" class="span3">
                </div>
              </div>
              <div class="controls">
                <div class="input-prepend"> <span class="add-on"><i class="icon-lock"></i></span>
                  <input type="password" placeholder="Password" class="span3">
                </div>
              </div>
            </div>
            </fieldset>
            <hr class="dashed">
            <button class="btn btn-info"><i class="icon-twitter"></i> Login with Twitter</button>
            <button class="btn btn-danger"><i class="icon-google-plus"></i> Login with Google</button>
          </div>
          <div class="modal-footer">
            <button class="btn btn-warning pull-left">Forgot Your Password?</button>
            <a href="index.html" class="btn btn-primary">Log In</a> </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/pricing.html.erb
<div id="header">
  <div class="container">
    <div class="row">
      <div class="span12">
        <h1>Plans and Pricing</h1>
      </div>
    </div>
  </div>
</div>
<div id="content" class="pricing-padding30">
  <div class="container">
    <div class="row">
      <div class="span4">
        <div class="product-plan">
          <ul class="unstyled plans">
            <li>
              <div class="name">
                <h3>Small</h3>
              </div>
            </li>
            <li>
              <div class="price">
                <h3>$0 <small>/ for life!</small></h3>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-hdd"></i> Storage <span class="pull-right">250 MB</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-dashboard"></i> Bandwidth <span class="pull-right">5 GB</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-user-md"></i> Support <span class="pull-right">24/7/365</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-upload"></i> Uptime <span class="pull-right">99%</span></h4>
              </div>
            </li>
            <li>
              <div class="action">
                <button class="btn btn-primary btn-action">Order Now</button>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="span4">
        <div class="product-plan popular">
          <ul class="unstyled plans">
            <li>
              <div class="name">
                <h3>Medium</h3>
              </div>
            </li>
            <li>
              <div class="price">
                <h3>$10 <small>/ month</small></h3>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-hdd"></i> Storage <span class="pull-right">5 GB</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-dashboard"></i> Bandwidth <span class="pull-right">100 GB</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-user-md"></i> Support <span class="pull-right">24/7/365</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-upload"></i> Uptime <span class="pull-right">99%</span></h4>
              </div>
            </li>
            <li>
              <div class="action">
                <button class="btn btn-primary btn-action">Order Now</button>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="span4">
        <div class="product-plan">
          <ul class="unstyled plans">
            <li>
              <div class="name">
                <h3>Large</h3>
              </div>
            </li>
            <li>
              <div class="price">
                <h3>$50 <small>/ month</small></h3>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-hdd"></i> Storage <span class="pull-right">25 GB</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-dashboard"></i> Bandwidth <span class="pull-right">500 GB</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-user-md"></i> Support <span class="pull-right">24/7/365</span></h4>
              </div>
            </li>
            <li>
              <div class="feature">
                <h4><i class="icon-upload"></i> Uptime <span class="pull-right">99%</span></h4>
              </div>
            </li>
            <li>
              <div class="action">
                <button class="btn btn-primary btn-action">Order Now</button>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="footer">
  <div class="container">
    <div class="row">
      <div class="span3">
        <h3>Quick Links</h3>
        <ul>
          <li><a href="<%= root_path %>">Home</a></li>
          <li><a href="<%= pages_about_path %>">About Us</a></li>
          <li><a href="<%= pages_features_path %>">Features</a></li>
          <li><a href="<%= pages_pricing_path %>">Pricing</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Company</h3>
        <ul>
          <li><a href="#">Privacy Policy</a></li>
          <li><a href="#">Terms of Use</a></li>
          <li><a href="#">Faq</a></li>
        </ul>
      </div>
      <div class="span3">
        <h3>Social Media</h3>
        <ul>
          <li><a href="#">Facebook</a></li>
          <li><a href="http://www.twitter.com/railsview">Twitter</a></li>
          <li><a href="#">Dribbble</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div id="copywrite">
  <div class="container">
    <div class="row">
      <div class="span12">
        <p>&copy; Mini Ruby <span id="totop" class="pull-right">Back to Top</span></p>
      </div>
    </div>
  </div>
</div>

app/views/pages/register.html.erb
<div id="content" class="txt-middle">
  <div class="container">
    <div class="row">
      <div class="span12">
        <div class="modal modal-flat">
          <div class="modal-header">
            <h3>Become a Bounce Member</h3>
          </div>
          <div class="modal-body">
            <button class="btn btn-info"><i class="icon-twitter"></i> Join using Twitter</button>
            <button class="btn btn-danger"><i class="icon-google-plus"></i> Join using Google</button>
            <hr class="dashed">
            <p class="text-info">create an account for free below</p>
            <fieldset>
            <div class="control-group">
              <div class="controls">
                <input type="text" placeholder="Your First Name" class="span5">
              </div>
              <div class="controls">
                <input type="text" placeholder="Your Last Name" class="span5">
              </div>
              <div class="controls">
                <input type="text" placeholder="Your Email" class="span5">
              </div>
              <div class="controls">
                <input type="password" placeholder="Password" class="span5">
              </div>
            </div>
            </fieldset>
          </div>
          <div class="modal-footer"> <a href="login.html" class="btn btn-warning pull-left">Already a Member?</a> <a href="index.html" class="btn btn-primary">Register!</a> </div>
        </div>
      </div>
    </div>
  </div>
</div>